[package]
name = "viewlastlog"
version = "0.1.2"
edition = "2021"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
colored = "2.0"
crossterm = "0.23.2"
chrono = "0.4"
getch = "0.3.1"
glob = "0.3.0"
